### ISSUE TITLE
on setup page ch.qos.logback:logback-classic show not installed

### ISSUE THREAD

**Issue by a754579830** [px3l/BIMserver#1]
Required dependency ch.qos.logback:logback-classic is not installed

**Comment by joriws** [comment]
Yes, this prevents initial setup to complete. I am running docker-version

Setting up...
Setting up admin account...
Admin account successfully setup
Skipping email setup...
Installing all extended data schemas...

Installing plugins...

Installing IfcPlugins...
Required dependency ch.qos.logback:logback-classic is not installed
Setup aborted

--

08:35:08 ERROR [PluginInterface.installPluginBundle]:                                                                                  (InstallPluginBundle.java:46)
java.lang.Exception: Required dependency ch.qos.logback:logback-classic is not installed
        at org.bimserver.plugins.PluginManager.install(PluginManager.java:1413) ~[shared-1.5.63.jar:na]
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:44) [bimserver-1.5.63.jar:na]
        at org.bimserver.database.actions.InstallPluginBundle.execute(InstallPluginBundle.java:18) [bimserver-1.5.63.jar:na]
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:698) [bimserver-1.5.63.jar:na]
        at org.bimserver.database.DatabaseSession.executeAndCommitAction(DatabaseSession.java:690) [bimserver-1.5.63.jar:na]
        at org.bimserver.webservices.impl.PluginServiceImpl.installPluginBundle(PluginServiceImpl.java:1453) [bimserver-1.5.63.jar:na]
        at org.bimserver.generated.PluginInterfaceReflector1.callMethod(PluginInterfaceReflector1.java) [shared-1.5.63.jar:na]
        at org.bimserver.shared.meta.SMethod.invoke(SMethod.java:213) [pluginbase-1.5.63.jar:na]
        at org.bimserver.JsonHandler.processSingleRequest(JsonHandler.java:137) [bimserver-1.5.63.jar:na]
        at org.bimserver.JsonHandler.execute(JsonHandler.java:60) [bimserver-1.5.63.jar:na]
        at org.bimserver.servlets.JsonApiServlet.service(JsonApiServlet.java:70) [bimserver-1.5.63.jar:na]
        at org.bimserver.servlets.RootServlet.service(RootServlet.java:136) [bimserver-1.5.63.jar:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729) [servlet-api.jar:na]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:292) [catalina.jar:8.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.39]
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52) [tomcat-websocket.jar:8.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:240) [catalina.jar:8.0.39]
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:207) [catalina.jar:8.0.39]
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:212) [catalina.jar:8.0.39]
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.39]
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.39]
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141) [catalina.jar:8.0.39]
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.39]
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.39]
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.39]
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:509) [catalina.jar:8.0.39]
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1104) [tomcat-coyote.jar:8.0.39]
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:684) [tomcat-coyote.jar:8.0.39]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1520) [tomcat-coyote.jar:8.0.39]
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1476) [tomcat-coyote.jar:8.0.39]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.39]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
